version: '3.9'

services:

  prometheus:
    image: ubuntu/prometheus
    container_name: prometheus
    ports:
      - "30090:9090"
    environment:
      - TZ=UTC
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "30091:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana
  