FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.1

ENV xpack.monitoring.enabled=true
ENV xpack.watcher.enabled=false
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false
ENV discovery.type=single-node
